#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Chart_GettingStarted.Resource", IsApplication=true)]

namespace Chart_GettingStarted
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Charts.Resource.Animation.SfChart_Fade_In = global::Chart_GettingStarted.Resource.Animation.SfChart_Fade_In;
			global::Com.Syncfusion.Charts.Resource.Animation.SfChart_Fade_Out = global::Chart_GettingStarted.Resource.Animation.SfChart_Fade_Out;
			global::Com.Syncfusion.Charts.Resource.Animation.SfChart_Scale_In = global::Chart_GettingStarted.Resource.Animation.SfChart_Scale_In;
			global::Com.Syncfusion.Charts.Resource.Animation.SfChart_Scale_Out = global::Chart_GettingStarted.Resource.Animation.SfChart_Scale_Out;
			global::Com.Syncfusion.Charts.Resource.Attribute.colorPalette = global::Chart_GettingStarted.Resource.Attribute.colorPalette;
			global::Com.Syncfusion.Charts.Resource.Attribute.deferredUpdateDelay = global::Chart_GettingStarted.Resource.Attribute.deferredUpdateDelay;
			global::Com.Syncfusion.Charts.Resource.Attribute.deferredUpdateEnabled = global::Chart_GettingStarted.Resource.Attribute.deferredUpdateEnabled;
			global::Com.Syncfusion.Charts.Resource.Attribute.enableTooltip = global::Chart_GettingStarted.Resource.Attribute.enableTooltip;
			global::Com.Syncfusion.Charts.Resource.Attribute.enableTrackball = global::Chart_GettingStarted.Resource.Attribute.enableTrackball;
			global::Com.Syncfusion.Charts.Resource.Attribute.enableZooming = global::Chart_GettingStarted.Resource.Attribute.enableZooming;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbBackground = global::Chart_GettingStarted.Resource.Attribute.leftThumbBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbHeight = global::Chart_GettingStarted.Resource.Attribute.leftThumbHeight;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbLineColor = global::Chart_GettingStarted.Resource.Attribute.leftThumbLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbLineWidth = global::Chart_GettingStarted.Resource.Attribute.leftThumbLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbStroke = global::Chart_GettingStarted.Resource.Attribute.leftThumbStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.leftThumbStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftThumbWidth = global::Chart_GettingStarted.Resource.Attribute.leftThumbWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipBackgroundColor = global::Chart_GettingStarted.Resource.Attribute.leftTooltipBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipMargin = global::Chart_GettingStarted.Resource.Attribute.leftTooltipMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipStrokeColor = global::Chart_GettingStarted.Resource.Attribute.leftTooltipStrokeColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.leftTooltipStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipTextColor = global::Chart_GettingStarted.Resource.Attribute.leftTooltipTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.leftTooltipTextSize = global::Chart_GettingStarted.Resource.Attribute.leftTooltipTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendDockPosition = global::Chart_GettingStarted.Resource.Attribute.legendDockPosition;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendIconHeight = global::Chart_GettingStarted.Resource.Attribute.legendIconHeight;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendIconWidth = global::Chart_GettingStarted.Resource.Attribute.legendIconWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendItemMarginBottom = global::Chart_GettingStarted.Resource.Attribute.legendItemMarginBottom;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendItemMarginLeft = global::Chart_GettingStarted.Resource.Attribute.legendItemMarginLeft;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendItemMarginRight = global::Chart_GettingStarted.Resource.Attribute.legendItemMarginRight;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendItemMarginTop = global::Chart_GettingStarted.Resource.Attribute.legendItemMarginTop;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendOrientation = global::Chart_GettingStarted.Resource.Attribute.legendOrientation;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendTitleText = global::Chart_GettingStarted.Resource.Attribute.legendTitleText;
			global::Com.Syncfusion.Charts.Resource.Attribute.legendVisibility = global::Chart_GettingStarted.Resource.Attribute.legendVisibility;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleGridLineColor = global::Chart_GettingStarted.Resource.Attribute.majorScaleGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleGridLineWidth = global::Chart_GettingStarted.Resource.Attribute.majorScaleGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelAlignment = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelAlignment;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelBackground = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelFormat = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelFormat;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelMargin = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelStroke = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelTextColor = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleLabelTextSize = global::Chart_GettingStarted.Resource.Attribute.majorScaleLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScalePosition = global::Chart_GettingStarted.Resource.Attribute.majorScalePosition;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelBackground = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelMargin = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelStroke = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelTextColor = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleSelectedLabelTextSize = global::Chart_GettingStarted.Resource.Attribute.majorScaleSelectedLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleTickColor = global::Chart_GettingStarted.Resource.Attribute.majorScaleTickColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleTickWidth = global::Chart_GettingStarted.Resource.Attribute.majorScaleTickWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.majorScaleVisibility = global::Chart_GettingStarted.Resource.Attribute.majorScaleVisibility;
			global::Com.Syncfusion.Charts.Resource.Attribute.maximumValue = global::Chart_GettingStarted.Resource.Attribute.maximumValue;
			global::Com.Syncfusion.Charts.Resource.Attribute.minimumValue = global::Chart_GettingStarted.Resource.Attribute.minimumValue;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleGridLineColor = global::Chart_GettingStarted.Resource.Attribute.minorScaleGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleGridLineWidth = global::Chart_GettingStarted.Resource.Attribute.minorScaleGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelAlignment = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelAlignment;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelBackground = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelFormat = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelFormat;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelMargin = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelStroke = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelTextColor = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleLabelTextSize = global::Chart_GettingStarted.Resource.Attribute.minorScaleLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScalePosition = global::Chart_GettingStarted.Resource.Attribute.minorScalePosition;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelBackground = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelMargin = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelStroke = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelTextColor = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleSelectedLabelTextSize = global::Chart_GettingStarted.Resource.Attribute.minorScaleSelectedLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleTickColor = global::Chart_GettingStarted.Resource.Attribute.minorScaleTickColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleTickWidth = global::Chart_GettingStarted.Resource.Attribute.minorScaleTickWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.minorScaleVisibility = global::Chart_GettingStarted.Resource.Attribute.minorScaleVisibility;
			global::Com.Syncfusion.Charts.Resource.Attribute.overlayColor = global::Chart_GettingStarted.Resource.Attribute.overlayColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbBackground = global::Chart_GettingStarted.Resource.Attribute.rightThumbBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbHeight = global::Chart_GettingStarted.Resource.Attribute.rightThumbHeight;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbLineColor = global::Chart_GettingStarted.Resource.Attribute.rightThumbLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbLineWidth = global::Chart_GettingStarted.Resource.Attribute.rightThumbLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbStroke = global::Chart_GettingStarted.Resource.Attribute.rightThumbStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.rightThumbStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightThumbWidth = global::Chart_GettingStarted.Resource.Attribute.rightThumbWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipBackground = global::Chart_GettingStarted.Resource.Attribute.rightTooltipBackground;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipMargin = global::Chart_GettingStarted.Resource.Attribute.rightTooltipMargin;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipStroke = global::Chart_GettingStarted.Resource.Attribute.rightTooltipStroke;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipStrokeWidth = global::Chart_GettingStarted.Resource.Attribute.rightTooltipStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipTextColor = global::Chart_GettingStarted.Resource.Attribute.rightTooltipTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.rightTooltipTextSize = global::Chart_GettingStarted.Resource.Attribute.rightTooltipTextSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.showMajorGridLines = global::Chart_GettingStarted.Resource.Attribute.showMajorGridLines;
			global::Com.Syncfusion.Charts.Resource.Attribute.showMinorGridLines = global::Chart_GettingStarted.Resource.Attribute.showMinorGridLines;
			global::Com.Syncfusion.Charts.Resource.Attribute.titleBackgroundColor = global::Chart_GettingStarted.Resource.Attribute.titleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.titleColor = global::Chart_GettingStarted.Resource.Attribute.titleColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.titlePaddingBottom = global::Chart_GettingStarted.Resource.Attribute.titlePaddingBottom;
			global::Com.Syncfusion.Charts.Resource.Attribute.titlePaddingLeft = global::Chart_GettingStarted.Resource.Attribute.titlePaddingLeft;
			global::Com.Syncfusion.Charts.Resource.Attribute.titlePaddingRight = global::Chart_GettingStarted.Resource.Attribute.titlePaddingRight;
			global::Com.Syncfusion.Charts.Resource.Attribute.titlePaddingTop = global::Chart_GettingStarted.Resource.Attribute.titlePaddingTop;
			global::Com.Syncfusion.Charts.Resource.Attribute.titleSize = global::Chart_GettingStarted.Resource.Attribute.titleSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.titleText = global::Chart_GettingStarted.Resource.Attribute.titleText;
			global::Com.Syncfusion.Charts.Resource.Attribute.tooltipDisplayMode = global::Chart_GettingStarted.Resource.Attribute.tooltipDisplayMode;
			global::Com.Syncfusion.Charts.Resource.Attribute.tooltipFormat = global::Chart_GettingStarted.Resource.Attribute.tooltipFormat;
			global::Com.Syncfusion.Charts.Resource.Attribute.viewRangeEnd = global::Chart_GettingStarted.Resource.Attribute.viewRangeEnd;
			global::Com.Syncfusion.Charts.Resource.Attribute.viewRangeStart = global::Chart_GettingStarted.Resource.Attribute.viewRangeStart;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxis = global::Chart_GettingStarted.Resource.Attribute.xAxis;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisLineColor = global::Chart_GettingStarted.Resource.Attribute.xAxisLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisLineWidth = global::Chart_GettingStarted.Resource.Attribute.xAxisLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisMajorGridLineColor = global::Chart_GettingStarted.Resource.Attribute.xAxisMajorGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisMajorGridLineWidth = global::Chart_GettingStarted.Resource.Attribute.xAxisMajorGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisTitleBackgroundColor = global::Chart_GettingStarted.Resource.Attribute.xAxisTitleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisTitleSize = global::Chart_GettingStarted.Resource.Attribute.xAxisTitleSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisTitleText = global::Chart_GettingStarted.Resource.Attribute.xAxisTitleText;
			global::Com.Syncfusion.Charts.Resource.Attribute.xAxisTitleTextColor = global::Chart_GettingStarted.Resource.Attribute.xAxisTitleTextColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxis = global::Chart_GettingStarted.Resource.Attribute.yAxis;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisLineColor = global::Chart_GettingStarted.Resource.Attribute.yAxisLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisLineWidth = global::Chart_GettingStarted.Resource.Attribute.yAxisLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisMajorGridLineColor = global::Chart_GettingStarted.Resource.Attribute.yAxisMajorGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisMajorGridLineWidth = global::Chart_GettingStarted.Resource.Attribute.yAxisMajorGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisTitleBackgroundColor = global::Chart_GettingStarted.Resource.Attribute.yAxisTitleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisTitleSize = global::Chart_GettingStarted.Resource.Attribute.yAxisTitleSize;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisTitleText = global::Chart_GettingStarted.Resource.Attribute.yAxisTitleText;
			global::Com.Syncfusion.Charts.Resource.Attribute.yAxisTitleTextColor = global::Chart_GettingStarted.Resource.Attribute.yAxisTitleTextColor;
			global::Com.Syncfusion.Charts.Resource.Id.always = global::Chart_GettingStarted.Resource.Id.always;
			global::Com.Syncfusion.Charts.Resource.Id.annotationLayout = global::Chart_GettingStarted.Resource.Id.annotationLayout;
			global::Com.Syncfusion.Charts.Resource.Id.auto = global::Chart_GettingStarted.Resource.Id.auto;
			global::Com.Syncfusion.Charts.Resource.Id.axisLayout = global::Chart_GettingStarted.Resource.Id.axisLayout;
			global::Com.Syncfusion.Charts.Resource.Id.bottom = global::Chart_GettingStarted.Resource.Id.bottom;
			global::Com.Syncfusion.Charts.Resource.Id.bottom_labels = global::Chart_GettingStarted.Resource.Id.bottom_labels;
			global::Com.Syncfusion.Charts.Resource.Id.category = global::Chart_GettingStarted.Resource.Id.category;
			global::Com.Syncfusion.Charts.Resource.Id.center = global::Chart_GettingStarted.Resource.Id.center;
			global::Com.Syncfusion.Charts.Resource.Id.chartBehaviorLayout = global::Chart_GettingStarted.Resource.Id.chartBehaviorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.chartLegendScrollView = global::Chart_GettingStarted.Resource.Id.chartLegendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.content = global::Chart_GettingStarted.Resource.Id.content;
			global::Com.Syncfusion.Charts.Resource.Id.custom = global::Chart_GettingStarted.Resource.Id.custom;
			global::Com.Syncfusion.Charts.Resource.Id.dataMarkerLayout = global::Chart_GettingStarted.Resource.Id.dataMarkerLayout;
			global::Com.Syncfusion.Charts.Resource.Id.dateTime = global::Chart_GettingStarted.Resource.Id.dateTime;
			global::Com.Syncfusion.Charts.Resource.Id.dateTimeCategory = global::Chart_GettingStarted.Resource.Id.dateTimeCategory;
			global::Com.Syncfusion.Charts.Resource.Id.floating = global::Chart_GettingStarted.Resource.Id.floating;
			global::Com.Syncfusion.Charts.Resource.Id.gone = global::Chart_GettingStarted.Resource.Id.gone;
			global::Com.Syncfusion.Charts.Resource.Id.gridLineLayout = global::Chart_GettingStarted.Resource.Id.gridLineLayout;
			global::Com.Syncfusion.Charts.Resource.Id.gridLinesLayout = global::Chart_GettingStarted.Resource.Id.gridLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.horizontal = global::Chart_GettingStarted.Resource.Id.horizontal;
			global::Com.Syncfusion.Charts.Resource.Id.iconView = global::Chart_GettingStarted.Resource.Id.iconView;
			global::Com.Syncfusion.Charts.Resource.Id.inside = global::Chart_GettingStarted.Resource.Id.inside;
			global::Com.Syncfusion.Charts.Resource.Id.label = global::Chart_GettingStarted.Resource.Id.label;
			global::Com.Syncfusion.Charts.Resource.Id.left = global::Chart_GettingStarted.Resource.Id.left;
			global::Com.Syncfusion.Charts.Resource.Id.legendHeader = global::Chart_GettingStarted.Resource.Id.legendHeader;
			global::Com.Syncfusion.Charts.Resource.Id.legendItemsLayout = global::Chart_GettingStarted.Resource.Id.legendItemsLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendLayout = global::Chart_GettingStarted.Resource.Id.legendLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendScrollView = global::Chart_GettingStarted.Resource.Id.legendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.legendViewGroup = global::Chart_GettingStarted.Resource.Id.legendViewGroup;
			global::Com.Syncfusion.Charts.Resource.Id.logarithmic = global::Chart_GettingStarted.Resource.Id.logarithmic;
			global::Com.Syncfusion.Charts.Resource.Id.metro = global::Chart_GettingStarted.Resource.Id.metro;
			global::Com.Syncfusion.Charts.Resource.Id.natural = global::Chart_GettingStarted.Resource.Id.natural;
			global::Com.Syncfusion.Charts.Resource.Id.none = global::Chart_GettingStarted.Resource.Id.none;
			global::Com.Syncfusion.Charts.Resource.Id.numerical = global::Chart_GettingStarted.Resource.Id.numerical;
			global::Com.Syncfusion.Charts.Resource.Id.onDemand = global::Chart_GettingStarted.Resource.Id.onDemand;
			global::Com.Syncfusion.Charts.Resource.Id.outside = global::Chart_GettingStarted.Resource.Id.outside;
			global::Com.Syncfusion.Charts.Resource.Id.pineapple = global::Chart_GettingStarted.Resource.Id.pineapple;
			global::Com.Syncfusion.Charts.Resource.Id.right = global::Chart_GettingStarted.Resource.Id.right;
			global::Com.Syncfusion.Charts.Resource.Id.rootLayout = global::Chart_GettingStarted.Resource.Id.rootLayout;
			global::Com.Syncfusion.Charts.Resource.Id.seriesLayout = global::Chart_GettingStarted.Resource.Id.seriesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.stripLinesLayout = global::Chart_GettingStarted.Resource.Id.stripLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.technicalIndicatorLayout = global::Chart_GettingStarted.Resource.Id.technicalIndicatorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.thumbLayout = global::Chart_GettingStarted.Resource.Id.thumbLayout;
			global::Com.Syncfusion.Charts.Resource.Id.titleLayout = global::Chart_GettingStarted.Resource.Id.titleLayout;
			global::Com.Syncfusion.Charts.Resource.Id.tomatoSpectrum = global::Chart_GettingStarted.Resource.Id.tomatoSpectrum;
			global::Com.Syncfusion.Charts.Resource.Id.top = global::Chart_GettingStarted.Resource.Id.top;
			global::Com.Syncfusion.Charts.Resource.Id.top_labels = global::Chart_GettingStarted.Resource.Id.top_labels;
			global::Com.Syncfusion.Charts.Resource.Id.vertical = global::Chart_GettingStarted.Resource.Id.vertical;
			global::Com.Syncfusion.Charts.Resource.Id.visible = global::Chart_GettingStarted.Resource.Id.visible;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_layout = global::Chart_GettingStarted.Resource.Layout.chart_layout;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend = global::Chart_GettingStarted.Resource.Layout.chart_legend;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend_item = global::Chart_GettingStarted.Resource.Layout.chart_legend_item;
			global::Com.Syncfusion.Charts.Resource.Layout.range_navigator_layout = global::Chart_GettingStarted.Resource.Layout.range_navigator_layout;
			global::Com.Syncfusion.Charts.Resource.String.q = global::Chart_GettingStarted.Resource.String.q;
			global::Com.Syncfusion.Charts.Resource.String.quarter = global::Chart_GettingStarted.Resource.String.quarter;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_Median_label = global::Chart_GettingStarted.Resource.String.sfchart_Median_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_Q1_label = global::Chart_GettingStarted.Resource.String.sfchart_Q1_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_Q3_label = global::Chart_GettingStarted.Resource.String.sfchart_Q3_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_close_label = global::Chart_GettingStarted.Resource.String.sfchart_close_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_decrease_label = global::Chart_GettingStarted.Resource.String.sfchart_decrease_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_high_label = global::Chart_GettingStarted.Resource.String.sfchart_high_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_increase_label = global::Chart_GettingStarted.Resource.String.sfchart_increase_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_low_label = global::Chart_GettingStarted.Resource.String.sfchart_low_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_maximum_label = global::Chart_GettingStarted.Resource.String.sfchart_maximum_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_minimum_label = global::Chart_GettingStarted.Resource.String.sfchart_minimum_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_open_label = global::Chart_GettingStarted.Resource.String.sfchart_open_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_others_label = global::Chart_GettingStarted.Resource.String.sfchart_others_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_total_label = global::Chart_GettingStarted.Resource.String.sfchart_total_label;
			global::Com.Syncfusion.Charts.Resource.String.w = global::Chart_GettingStarted.Resource.String.w;
			global::Com.Syncfusion.Charts.Resource.String.week = global::Chart_GettingStarted.Resource.String.week;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart = global::Chart_GettingStarted.Resource.Styleable.SfChart;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_colorPalette = global::Chart_GettingStarted.Resource.Styleable.SfChart_colorPalette;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_enableTrackball = global::Chart_GettingStarted.Resource.Styleable.SfChart_enableTrackball;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_enableZooming = global::Chart_GettingStarted.Resource.Styleable.SfChart_enableZooming;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendDockPosition = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendDockPosition;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendIconHeight = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendIconHeight;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendIconWidth = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendIconWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendItemMarginBottom = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendItemMarginBottom;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendItemMarginLeft = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendItemMarginLeft;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendItemMarginRight = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendItemMarginRight;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendItemMarginTop = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendItemMarginTop;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendOrientation = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendOrientation;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendTitleText = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendTitleText;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_legendVisibility = global::Chart_GettingStarted.Resource.Styleable.SfChart_legendVisibility;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titleBackgroundColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_titleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titleColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_titleColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titlePaddingBottom = global::Chart_GettingStarted.Resource.Styleable.SfChart_titlePaddingBottom;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titlePaddingLeft = global::Chart_GettingStarted.Resource.Styleable.SfChart_titlePaddingLeft;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titlePaddingRight = global::Chart_GettingStarted.Resource.Styleable.SfChart_titlePaddingRight;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titlePaddingTop = global::Chart_GettingStarted.Resource.Styleable.SfChart_titlePaddingTop;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titleSize = global::Chart_GettingStarted.Resource.Styleable.SfChart_titleSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_titleText = global::Chart_GettingStarted.Resource.Styleable.SfChart_titleText;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxis = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxis;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisLineColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisMajorGridLineColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisMajorGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisMajorGridLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisMajorGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisTitleBackgroundColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisTitleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisTitleSize = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisTitleSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisTitleText = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisTitleText;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_xAxisTitleTextColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_xAxisTitleTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxis = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxis;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisLineColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisMajorGridLineColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisMajorGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisMajorGridLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisMajorGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisTitleBackgroundColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisTitleBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisTitleSize = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisTitleSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisTitleText = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisTitleText;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfChart_yAxisTitleTextColor = global::Chart_GettingStarted.Resource.Styleable.SfChart_yAxisTitleTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_deferredUpdateDelay = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_deferredUpdateDelay;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_deferredUpdateEnabled = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_deferredUpdateEnabled;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_enableTooltip = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_enableTooltip;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbHeight = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbHeight;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbLineColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftThumbWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipBackgroundColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipBackgroundColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipStrokeColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipStrokeColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_leftTooltipTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleGridLineColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleGridLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelAlignment = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelAlignment;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelFormat = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelFormat;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScalePosition = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScalePosition;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleSelectedLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleTickColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleTickColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleTickWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleTickWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleVisibility = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_majorScaleVisibility;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_maximumValue = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_maximumValue;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minimumValue = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minimumValue;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleGridLineColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleGridLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleGridLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleGridLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelAlignment = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelAlignment;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelFormat = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelFormat;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScalePosition = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScalePosition;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleSelectedLabelTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleTickColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleTickColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleTickWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleTickWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleVisibility = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_minorScaleVisibility;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_overlayColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_overlayColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbHeight = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbHeight;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbLineColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbLineColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbLineWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbLineWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightThumbWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipBackground = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipBackground;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipMargin = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipMargin;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipStroke = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipStroke;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipStrokeWidth = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipStrokeWidth;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipTextColor = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipTextColor;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipTextSize = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_rightTooltipTextSize;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_showMajorGridLines = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_showMajorGridLines;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_showMinorGridLines = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_showMinorGridLines;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_tooltipDisplayMode = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_tooltipDisplayMode;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_tooltipFormat = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_tooltipFormat;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_viewRangeEnd = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_viewRangeEnd;
			global::Com.Syncfusion.Charts.Resource.Styleable.SfDateTimeRangeNavigator_viewRangeStart = global::Chart_GettingStarted.Resource.Styleable.SfDateTimeRangeNavigator_viewRangeStart;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SfChart_Fade_In = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SfChart_Fade_Out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SfChart_Scale_In = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SfChart_Scale_Out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010024
			public const int colorPalette = 2130772004;
			
			// aapt resource value: 0x7f010030
			public const int deferredUpdateDelay = 2130772016;
			
			// aapt resource value: 0x7f01002f
			public const int deferredUpdateEnabled = 2130772015;
			
			// aapt resource value: 0x7f01002c
			public const int enableTooltip = 2130772012;
			
			// aapt resource value: 0x7f010026
			public const int enableTrackball = 2130772006;
			
			// aapt resource value: 0x7f010025
			public const int enableZooming = 2130772005;
			
			// aapt resource value: 0x7f010033
			public const int leftThumbBackground = 2130772019;
			
			// aapt resource value: 0x7f010035
			public const int leftThumbHeight = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int leftThumbLineColor = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int leftThumbLineWidth = 2130772023;
			
			// aapt resource value: 0x7f010031
			public const int leftThumbStroke = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int leftThumbStrokeWidth = 2130772018;
			
			// aapt resource value: 0x7f010034
			public const int leftThumbWidth = 2130772020;
			
			// aapt resource value: 0x7f01006c
			public const int leftTooltipBackgroundColor = 2130772076;
			
			// aapt resource value: 0x7f010069
			public const int leftTooltipMargin = 2130772073;
			
			// aapt resource value: 0x7f01006d
			public const int leftTooltipStrokeColor = 2130772077;
			
			// aapt resource value: 0x7f01006e
			public const int leftTooltipStrokeWidth = 2130772078;
			
			// aapt resource value: 0x7f01006b
			public const int leftTooltipTextColor = 2130772075;
			
			// aapt resource value: 0x7f01006a
			public const int leftTooltipTextSize = 2130772074;
			
			// aapt resource value: 0x7f01001a
			public const int legendDockPosition = 2130771994;
			
			// aapt resource value: 0x7f010014
			public const int legendIconHeight = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int legendIconWidth = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int legendItemMarginBottom = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int legendItemMarginLeft = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int legendItemMarginRight = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int legendItemMarginTop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int legendOrientation = 2130771995;
			
			// aapt resource value: 0x7f010013
			public const int legendTitleText = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int legendVisibility = 2130771986;
			
			// aapt resource value: 0x7f010050
			public const int majorScaleGridLineColor = 2130772048;
			
			// aapt resource value: 0x7f010051
			public const int majorScaleGridLineWidth = 2130772049;
			
			// aapt resource value: 0x7f010042
			public const int majorScaleLabelAlignment = 2130772034;
			
			// aapt resource value: 0x7f010046
			public const int majorScaleLabelBackground = 2130772038;
			
			// aapt resource value: 0x7f010041
			public const int majorScaleLabelFormat = 2130772033;
			
			// aapt resource value: 0x7f010043
			public const int majorScaleLabelMargin = 2130772035;
			
			// aapt resource value: 0x7f010047
			public const int majorScaleLabelStroke = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int majorScaleLabelStrokeWidth = 2130772040;
			
			// aapt resource value: 0x7f010045
			public const int majorScaleLabelTextColor = 2130772037;
			
			// aapt resource value: 0x7f010044
			public const int majorScaleLabelTextSize = 2130772036;
			
			// aapt resource value: 0x7f010040
			public const int majorScalePosition = 2130772032;
			
			// aapt resource value: 0x7f01004c
			public const int majorScaleSelectedLabelBackground = 2130772044;
			
			// aapt resource value: 0x7f010049
			public const int majorScaleSelectedLabelMargin = 2130772041;
			
			// aapt resource value: 0x7f01004d
			public const int majorScaleSelectedLabelStroke = 2130772045;
			
			// aapt resource value: 0x7f01004e
			public const int majorScaleSelectedLabelStrokeWidth = 2130772046;
			
			// aapt resource value: 0x7f01004b
			public const int majorScaleSelectedLabelTextColor = 2130772043;
			
			// aapt resource value: 0x7f01004a
			public const int majorScaleSelectedLabelTextSize = 2130772042;
			
			// aapt resource value: 0x7f010053
			public const int majorScaleTickColor = 2130772051;
			
			// aapt resource value: 0x7f010052
			public const int majorScaleTickWidth = 2130772050;
			
			// aapt resource value: 0x7f01003f
			public const int majorScaleVisibility = 2130772031;
			
			// aapt resource value: 0x7f010027
			public const int maximumValue = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int minimumValue = 2130772008;
			
			// aapt resource value: 0x7f010065
			public const int minorScaleGridLineColor = 2130772069;
			
			// aapt resource value: 0x7f010066
			public const int minorScaleGridLineWidth = 2130772070;
			
			// aapt resource value: 0x7f010057
			public const int minorScaleLabelAlignment = 2130772055;
			
			// aapt resource value: 0x7f01005b
			public const int minorScaleLabelBackground = 2130772059;
			
			// aapt resource value: 0x7f010056
			public const int minorScaleLabelFormat = 2130772054;
			
			// aapt resource value: 0x7f010058
			public const int minorScaleLabelMargin = 2130772056;
			
			// aapt resource value: 0x7f01005c
			public const int minorScaleLabelStroke = 2130772060;
			
			// aapt resource value: 0x7f01005d
			public const int minorScaleLabelStrokeWidth = 2130772061;
			
			// aapt resource value: 0x7f01005a
			public const int minorScaleLabelTextColor = 2130772058;
			
			// aapt resource value: 0x7f010059
			public const int minorScaleLabelTextSize = 2130772057;
			
			// aapt resource value: 0x7f010055
			public const int minorScalePosition = 2130772053;
			
			// aapt resource value: 0x7f010061
			public const int minorScaleSelectedLabelBackground = 2130772065;
			
			// aapt resource value: 0x7f01005e
			public const int minorScaleSelectedLabelMargin = 2130772062;
			
			// aapt resource value: 0x7f010062
			public const int minorScaleSelectedLabelStroke = 2130772066;
			
			// aapt resource value: 0x7f010063
			public const int minorScaleSelectedLabelStrokeWidth = 2130772067;
			
			// aapt resource value: 0x7f010060
			public const int minorScaleSelectedLabelTextColor = 2130772064;
			
			// aapt resource value: 0x7f01005f
			public const int minorScaleSelectedLabelTextSize = 2130772063;
			
			// aapt resource value: 0x7f010068
			public const int minorScaleTickColor = 2130772072;
			
			// aapt resource value: 0x7f010067
			public const int minorScaleTickWidth = 2130772071;
			
			// aapt resource value: 0x7f010054
			public const int minorScaleVisibility = 2130772052;
			
			// aapt resource value: 0x7f01002b
			public const int overlayColor = 2130772011;
			
			// aapt resource value: 0x7f01003a
			public const int rightThumbBackground = 2130772026;
			
			// aapt resource value: 0x7f01003c
			public const int rightThumbHeight = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public const int rightThumbLineColor = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int rightThumbLineWidth = 2130772030;
			
			// aapt resource value: 0x7f010038
			public const int rightThumbStroke = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int rightThumbStrokeWidth = 2130772025;
			
			// aapt resource value: 0x7f01003b
			public const int rightThumbWidth = 2130772027;
			
			// aapt resource value: 0x7f010072
			public const int rightTooltipBackground = 2130772082;
			
			// aapt resource value: 0x7f01006f
			public const int rightTooltipMargin = 2130772079;
			
			// aapt resource value: 0x7f010073
			public const int rightTooltipStroke = 2130772083;
			
			// aapt resource value: 0x7f010074
			public const int rightTooltipStrokeWidth = 2130772084;
			
			// aapt resource value: 0x7f010071
			public const int rightTooltipTextColor = 2130772081;
			
			// aapt resource value: 0x7f010070
			public const int rightTooltipTextSize = 2130772080;
			
			// aapt resource value: 0x7f01004f
			public const int showMajorGridLines = 2130772047;
			
			// aapt resource value: 0x7f010064
			public const int showMinorGridLines = 2130772068;
			
			// aapt resource value: 0x7f01001f
			public const int titleBackgroundColor = 2130771999;
			
			// aapt resource value: 0x7f01001d
			public const int titleColor = 2130771997;
			
			// aapt resource value: 0x7f010023
			public const int titlePaddingBottom = 2130772003;
			
			// aapt resource value: 0x7f010020
			public const int titlePaddingLeft = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int titlePaddingRight = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int titlePaddingTop = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int titleSize = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int titleText = 2130771996;
			
			// aapt resource value: 0x7f01002d
			public const int tooltipDisplayMode = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int tooltipFormat = 2130772014;
			
			// aapt resource value: 0x7f01002a
			public const int viewRangeEnd = 2130772010;
			
			// aapt resource value: 0x7f010029
			public const int viewRangeStart = 2130772009;
			
			// aapt resource value: 0x7f010000
			public const int xAxis = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public const int xAxisLineColor = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int xAxisLineWidth = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int xAxisMajorGridLineColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int xAxisMajorGridLineWidth = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int xAxisTitleBackgroundColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int xAxisTitleSize = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int xAxisTitleText = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int xAxisTitleTextColor = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int yAxis = 2130771969;
			
			// aapt resource value: 0x7f010010
			public const int yAxisLineColor = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int yAxisLineWidth = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int yAxisMajorGridLineColor = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int yAxisMajorGridLineWidth = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int yAxisTitleBackgroundColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int yAxisTitleSize = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int yAxisTitleText = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int yAxisTitleTextColor = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002c
			public const int RootLayout = 2131099692;
			
			// aapt resource value: 0x7f060015
			public const int always = 2131099669;
			
			// aapt resource value: 0x7f060024
			public const int annotationLayout = 2131099684;
			
			// aapt resource value: 0x7f06000c
			public const int auto = 2131099660;
			
			// aapt resource value: 0x7f060021
			public const int axisLayout = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int bottom = 2131099655;
			
			// aapt resource value: 0x7f060030
			public const int bottom_labels = 2131099696;
			
			// aapt resource value: 0x7f06002d
			public const int button = 2131099693;
			
			// aapt resource value: 0x7f060000
			public const int category = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int center = 2131099673;
			
			// aapt resource value: 0x7f06002e
			public const int chart = 2131099694;
			
			// aapt resource value: 0x7f060023
			public const int chartBehaviorLayout = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int chartLegendScrollView = 2131099687;
			
			// aapt resource value: 0x7f060031
			public const int content = 2131099697;
			
			// aapt resource value: 0x7f06000f
			public const int custom = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int dataMarkerLayout = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int dateTime = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dateTimeCategory = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int floating = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int gone = 2131099653;
			
			// aapt resource value: 0x7f06001c
			public const int gridLineLayout = 2131099676;
			
			// aapt resource value: 0x7f060032
			public const int gridLinesLayout = 2131099698;
			
			// aapt resource value: 0x7f06000d
			public const int horizontal = 2131099661;
			
			// aapt resource value: 0x7f06002a
			public const int iconView = 2131099690;
			
			// aapt resource value: 0x7f060017
			public const int inside = 2131099671;
			
			// aapt resource value: 0x7f06002b
			public const int label = 2131099691;
			
			// aapt resource value: 0x7f060009
			public const int left = 2131099657;
			
			// aapt resource value: 0x7f060026
			public const int legendHeader = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int legendItemsLayout = 2131099689;
			
			// aapt resource value: 0x7f060022
			public const int legendLayout = 2131099682;
			
			// aapt resource value: 0x7f060028
			public const int legendScrollView = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int legendViewGroup = 2131099685;
			
			// aapt resource value: 0x7f060003
			public const int logarithmic = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int metro = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int natural = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int none = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int numerical = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int onDemand = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int outside = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int pineapple = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int right = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int rootLayout = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int seriesLayout = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int stripLinesLayout = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int technicalIndicatorLayout = 2131099680;
			
			// aapt resource value: 0x7f060033
			public const int thumbLayout = 2131099699;
			
			// aapt resource value: 0x7f06001b
			public const int titleLayout = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int tomatoSpectrum = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int top = 2131099659;
			
			// aapt resource value: 0x7f06002f
			public const int top_labels = 2131099695;
			
			// aapt resource value: 0x7f06000e
			public const int vertical = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int visible = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int range_navigator_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int q = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int quarter = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int sfchart_Median_label = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int sfchart_Q1_label = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int sfchart_Q3_label = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int sfchart_close_label = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int sfchart_decrease_label = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int sfchart_high_label = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int sfchart_increase_label = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int sfchart_low_label = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int sfchart_maximum_label = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sfchart_minimum_label = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int sfchart_open_label = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int sfchart_others_label = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int sfchart_total_label = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int w = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int week = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SfChart = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 36
			public const int SfChart_colorPalette = 36;
			
			// aapt resource value: 38
			public const int SfChart_enableTrackball = 38;
			
			// aapt resource value: 37
			public const int SfChart_enableZooming = 37;
			
			// aapt resource value: 26
			public const int SfChart_legendDockPosition = 26;
			
			// aapt resource value: 20
			public const int SfChart_legendIconHeight = 20;
			
			// aapt resource value: 21
			public const int SfChart_legendIconWidth = 21;
			
			// aapt resource value: 22
			public const int SfChart_legendItemMarginBottom = 22;
			
			// aapt resource value: 23
			public const int SfChart_legendItemMarginLeft = 23;
			
			// aapt resource value: 24
			public const int SfChart_legendItemMarginRight = 24;
			
			// aapt resource value: 25
			public const int SfChart_legendItemMarginTop = 25;
			
			// aapt resource value: 27
			public const int SfChart_legendOrientation = 27;
			
			// aapt resource value: 19
			public const int SfChart_legendTitleText = 19;
			
			// aapt resource value: 18
			public const int SfChart_legendVisibility = 18;
			
			// aapt resource value: 31
			public const int SfChart_titleBackgroundColor = 31;
			
			// aapt resource value: 29
			public const int SfChart_titleColor = 29;
			
			// aapt resource value: 35
			public const int SfChart_titlePaddingBottom = 35;
			
			// aapt resource value: 32
			public const int SfChart_titlePaddingLeft = 32;
			
			// aapt resource value: 33
			public const int SfChart_titlePaddingRight = 33;
			
			// aapt resource value: 34
			public const int SfChart_titlePaddingTop = 34;
			
			// aapt resource value: 30
			public const int SfChart_titleSize = 30;
			
			// aapt resource value: 28
			public const int SfChart_titleText = 28;
			
			// aapt resource value: 0
			public const int SfChart_xAxis = 0;
			
			// aapt resource value: 12
			public const int SfChart_xAxisLineColor = 12;
			
			// aapt resource value: 13
			public const int SfChart_xAxisLineWidth = 13;
			
			// aapt resource value: 10
			public const int SfChart_xAxisMajorGridLineColor = 10;
			
			// aapt resource value: 11
			public const int SfChart_xAxisMajorGridLineWidth = 11;
			
			// aapt resource value: 5
			public const int SfChart_xAxisTitleBackgroundColor = 5;
			
			// aapt resource value: 4
			public const int SfChart_xAxisTitleSize = 4;
			
			// aapt resource value: 2
			public const int SfChart_xAxisTitleText = 2;
			
			// aapt resource value: 3
			public const int SfChart_xAxisTitleTextColor = 3;
			
			// aapt resource value: 1
			public const int SfChart_yAxis = 1;
			
			// aapt resource value: 16
			public const int SfChart_yAxisLineColor = 16;
			
			// aapt resource value: 17
			public const int SfChart_yAxisLineWidth = 17;
			
			// aapt resource value: 14
			public const int SfChart_yAxisMajorGridLineColor = 14;
			
			// aapt resource value: 15
			public const int SfChart_yAxisMajorGridLineWidth = 15;
			
			// aapt resource value: 9
			public const int SfChart_yAxisTitleBackgroundColor = 9;
			
			// aapt resource value: 8
			public const int SfChart_yAxisTitleSize = 8;
			
			// aapt resource value: 6
			public const int SfChart_yAxisTitleText = 6;
			
			// aapt resource value: 7
			public const int SfChart_yAxisTitleTextColor = 7;
			
			public static int[] SfDateTimeRangeNavigator = new int[] {
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061,
					2130772062,
					2130772063,
					2130772064,
					2130772065,
					2130772066,
					2130772067,
					2130772068,
					2130772069,
					2130772070,
					2130772071,
					2130772072,
					2130772073,
					2130772074,
					2130772075,
					2130772076,
					2130772077,
					2130772078,
					2130772079,
					2130772080,
					2130772081,
					2130772082,
					2130772083,
					2130772084};
			
			// aapt resource value: 9
			public const int SfDateTimeRangeNavigator_deferredUpdateDelay = 9;
			
			// aapt resource value: 8
			public const int SfDateTimeRangeNavigator_deferredUpdateEnabled = 8;
			
			// aapt resource value: 5
			public const int SfDateTimeRangeNavigator_enableTooltip = 5;
			
			// aapt resource value: 12
			public const int SfDateTimeRangeNavigator_leftThumbBackground = 12;
			
			// aapt resource value: 14
			public const int SfDateTimeRangeNavigator_leftThumbHeight = 14;
			
			// aapt resource value: 15
			public const int SfDateTimeRangeNavigator_leftThumbLineColor = 15;
			
			// aapt resource value: 16
			public const int SfDateTimeRangeNavigator_leftThumbLineWidth = 16;
			
			// aapt resource value: 10
			public const int SfDateTimeRangeNavigator_leftThumbStroke = 10;
			
			// aapt resource value: 11
			public const int SfDateTimeRangeNavigator_leftThumbStrokeWidth = 11;
			
			// aapt resource value: 13
			public const int SfDateTimeRangeNavigator_leftThumbWidth = 13;
			
			// aapt resource value: 69
			public const int SfDateTimeRangeNavigator_leftTooltipBackgroundColor = 69;
			
			// aapt resource value: 66
			public const int SfDateTimeRangeNavigator_leftTooltipMargin = 66;
			
			// aapt resource value: 70
			public const int SfDateTimeRangeNavigator_leftTooltipStrokeColor = 70;
			
			// aapt resource value: 71
			public const int SfDateTimeRangeNavigator_leftTooltipStrokeWidth = 71;
			
			// aapt resource value: 68
			public const int SfDateTimeRangeNavigator_leftTooltipTextColor = 68;
			
			// aapt resource value: 67
			public const int SfDateTimeRangeNavigator_leftTooltipTextSize = 67;
			
			// aapt resource value: 41
			public const int SfDateTimeRangeNavigator_majorScaleGridLineColor = 41;
			
			// aapt resource value: 42
			public const int SfDateTimeRangeNavigator_majorScaleGridLineWidth = 42;
			
			// aapt resource value: 27
			public const int SfDateTimeRangeNavigator_majorScaleLabelAlignment = 27;
			
			// aapt resource value: 31
			public const int SfDateTimeRangeNavigator_majorScaleLabelBackground = 31;
			
			// aapt resource value: 26
			public const int SfDateTimeRangeNavigator_majorScaleLabelFormat = 26;
			
			// aapt resource value: 28
			public const int SfDateTimeRangeNavigator_majorScaleLabelMargin = 28;
			
			// aapt resource value: 32
			public const int SfDateTimeRangeNavigator_majorScaleLabelStroke = 32;
			
			// aapt resource value: 33
			public const int SfDateTimeRangeNavigator_majorScaleLabelStrokeWidth = 33;
			
			// aapt resource value: 30
			public const int SfDateTimeRangeNavigator_majorScaleLabelTextColor = 30;
			
			// aapt resource value: 29
			public const int SfDateTimeRangeNavigator_majorScaleLabelTextSize = 29;
			
			// aapt resource value: 25
			public const int SfDateTimeRangeNavigator_majorScalePosition = 25;
			
			// aapt resource value: 37
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelBackground = 37;
			
			// aapt resource value: 34
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelMargin = 34;
			
			// aapt resource value: 38
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelStroke = 38;
			
			// aapt resource value: 39
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelStrokeWidth = 39;
			
			// aapt resource value: 36
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelTextColor = 36;
			
			// aapt resource value: 35
			public const int SfDateTimeRangeNavigator_majorScaleSelectedLabelTextSize = 35;
			
			// aapt resource value: 44
			public const int SfDateTimeRangeNavigator_majorScaleTickColor = 44;
			
			// aapt resource value: 43
			public const int SfDateTimeRangeNavigator_majorScaleTickWidth = 43;
			
			// aapt resource value: 24
			public const int SfDateTimeRangeNavigator_majorScaleVisibility = 24;
			
			// aapt resource value: 0
			public const int SfDateTimeRangeNavigator_maximumValue = 0;
			
			// aapt resource value: 1
			public const int SfDateTimeRangeNavigator_minimumValue = 1;
			
			// aapt resource value: 62
			public const int SfDateTimeRangeNavigator_minorScaleGridLineColor = 62;
			
			// aapt resource value: 63
			public const int SfDateTimeRangeNavigator_minorScaleGridLineWidth = 63;
			
			// aapt resource value: 48
			public const int SfDateTimeRangeNavigator_minorScaleLabelAlignment = 48;
			
			// aapt resource value: 52
			public const int SfDateTimeRangeNavigator_minorScaleLabelBackground = 52;
			
			// aapt resource value: 47
			public const int SfDateTimeRangeNavigator_minorScaleLabelFormat = 47;
			
			// aapt resource value: 49
			public const int SfDateTimeRangeNavigator_minorScaleLabelMargin = 49;
			
			// aapt resource value: 53
			public const int SfDateTimeRangeNavigator_minorScaleLabelStroke = 53;
			
			// aapt resource value: 54
			public const int SfDateTimeRangeNavigator_minorScaleLabelStrokeWidth = 54;
			
			// aapt resource value: 51
			public const int SfDateTimeRangeNavigator_minorScaleLabelTextColor = 51;
			
			// aapt resource value: 50
			public const int SfDateTimeRangeNavigator_minorScaleLabelTextSize = 50;
			
			// aapt resource value: 46
			public const int SfDateTimeRangeNavigator_minorScalePosition = 46;
			
			// aapt resource value: 58
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelBackground = 58;
			
			// aapt resource value: 55
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelMargin = 55;
			
			// aapt resource value: 59
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelStroke = 59;
			
			// aapt resource value: 60
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelStrokeWidth = 60;
			
			// aapt resource value: 57
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelTextColor = 57;
			
			// aapt resource value: 56
			public const int SfDateTimeRangeNavigator_minorScaleSelectedLabelTextSize = 56;
			
			// aapt resource value: 65
			public const int SfDateTimeRangeNavigator_minorScaleTickColor = 65;
			
			// aapt resource value: 64
			public const int SfDateTimeRangeNavigator_minorScaleTickWidth = 64;
			
			// aapt resource value: 45
			public const int SfDateTimeRangeNavigator_minorScaleVisibility = 45;
			
			// aapt resource value: 4
			public const int SfDateTimeRangeNavigator_overlayColor = 4;
			
			// aapt resource value: 19
			public const int SfDateTimeRangeNavigator_rightThumbBackground = 19;
			
			// aapt resource value: 21
			public const int SfDateTimeRangeNavigator_rightThumbHeight = 21;
			
			// aapt resource value: 22
			public const int SfDateTimeRangeNavigator_rightThumbLineColor = 22;
			
			// aapt resource value: 23
			public const int SfDateTimeRangeNavigator_rightThumbLineWidth = 23;
			
			// aapt resource value: 17
			public const int SfDateTimeRangeNavigator_rightThumbStroke = 17;
			
			// aapt resource value: 18
			public const int SfDateTimeRangeNavigator_rightThumbStrokeWidth = 18;
			
			// aapt resource value: 20
			public const int SfDateTimeRangeNavigator_rightThumbWidth = 20;
			
			// aapt resource value: 75
			public const int SfDateTimeRangeNavigator_rightTooltipBackground = 75;
			
			// aapt resource value: 72
			public const int SfDateTimeRangeNavigator_rightTooltipMargin = 72;
			
			// aapt resource value: 76
			public const int SfDateTimeRangeNavigator_rightTooltipStroke = 76;
			
			// aapt resource value: 77
			public const int SfDateTimeRangeNavigator_rightTooltipStrokeWidth = 77;
			
			// aapt resource value: 74
			public const int SfDateTimeRangeNavigator_rightTooltipTextColor = 74;
			
			// aapt resource value: 73
			public const int SfDateTimeRangeNavigator_rightTooltipTextSize = 73;
			
			// aapt resource value: 40
			public const int SfDateTimeRangeNavigator_showMajorGridLines = 40;
			
			// aapt resource value: 61
			public const int SfDateTimeRangeNavigator_showMinorGridLines = 61;
			
			// aapt resource value: 6
			public const int SfDateTimeRangeNavigator_tooltipDisplayMode = 6;
			
			// aapt resource value: 7
			public const int SfDateTimeRangeNavigator_tooltipFormat = 7;
			
			// aapt resource value: 3
			public const int SfDateTimeRangeNavigator_viewRangeEnd = 3;
			
			// aapt resource value: 2
			public const int SfDateTimeRangeNavigator_viewRangeStart = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
